### ISSUE TITLE
npm run build error,how to treat

### ISSUE THREAD

**Issue by minxiongxiong** [isekaidev/stable.art#58]
How should I pack it? Is npm run build? Report an error

 ERROR  Error: Build failed with errors.
Error: Build failed with errors.
    at E:\ai-progect\artboost-pscode\node_modules\@vue\cli-service\lib\commands\build\index.js:207:23
    at E:\ai-progect\artboost-pscode\node_modules\webpack\lib\webpack.js:148:8
    at E:\ai-progect\artboost-pscode\node_modules\webpack\lib\HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (E:\ai-progect\artboost-pscode\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (E:\ai-progect\artboost-pscode\node_modules\tapable\lib\Hook.js:18:14)
    at Cache.shutdown (E:\ai-progect\artboost-pscode\node_modules\webpack\lib\Cache.js:150:23)
    at E:\ai-progect\artboost-pscode\node_modules\webpack\lib\Compiler.js:1225:15
    at Hook.eval [as callAsync] (eval at create (E:\ai-progect\artboost-pscode\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (E:\ai-progect\artboost-pscode\node_modules\tapable\lib\Hook.js:18:14)
    at Compiler.close (E:\ai-progect\artboost-pscode\node_modules\webpack\lib\Compiler.js:1218:23)
    at E:\ai-progect\artboost-pscode\node_modules\webpack\lib\webpack.js:147:16
    at finalCallback (E:\ai-progect\artboost-pscode\node_modules\webpack\lib\Compiler.js:441:32)
    at E:\ai-progect\artboost-pscode\node_modules\webpack\lib\Compiler.js:458:13
    at Hook.eval [as callAsync] (eval at create (E:\ai-progect\artboost-pscode\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (E:\ai-progect\artboost-pscode\node_modules\tapable\lib\Hook.js:18:14)
    at onCompiled (E:\ai-progect\artboost-pscode\node_modules\webpack\lib\Compiler.js:456:21)
    at E:\ai-progect\artboost-pscode\node_modules\webpack\lib\Compiler.js:1196:17
    at Hook.eval [as callAsync] (eval at create (E:\ai-progect\artboost-pscode\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (E:\ai-progect\artboost-pscode\node_modules\tapable\lib\Hook.js:18:14)
    at E:\ai-progect\artboost-pscode\node_modules\webpack\lib\Compiler.js:1192:33
    at finalCallback (E:\ai-progect\artboost-pscode\node_modules\webpack\lib\Compilation.js:2787:11)
    at E:\ai-progect\artboost-pscode\node_modules\webpack\lib\Compilation.js:3092:11
    at Hook.eval [as callAsync] (eval at create (E:\ai-progect\artboost-pscode\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (E:\ai-progect\artboost-pscode\node_modules\tapable\lib\Hook.js:18:14)
    at E:\ai-progect\artboost-pscode\node_modules\webpack\lib\Compilation.js:3085:38
    at eval (eval at create (E:\ai-progect\artboost-pscode\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at eval (eval at create (E:\ai-progect\artboost-pscode\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:14:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by minxiongxiong** [comment]
eslint
